package fr.outadoc.aoc.yyyy

import fr.outadoc.aoc.scaffold.testStep1
import fr.outadoc.aoc.scaffold.testStep2
import kotlin.js.JsName
import kotlin.test.Test

class YearTests {
    @Test @JsName("testDay01Step1") fun `Day 01 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day01().testStep1()
    @Test @JsName("testDay01Step2") fun `Day 01 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day01().testStep2()
    @Test @JsName("testDay02Step1") fun `Day 02 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day02().testStep1()
    @Test @JsName("testDay02Step2") fun `Day 02 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day02().testStep2()
    @Test @JsName("testDay03Step1") fun `Day 03 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day03().testStep1()
    @Test @JsName("testDay03Step2") fun `Day 03 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day03().testStep2()
    @Test @JsName("testDay04Step1") fun `Day 04 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day04().testStep1()
    @Test @JsName("testDay04Step2") fun `Day 04 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day04().testStep2()
    @Test @JsName("testDay05Step1") fun `Day 05 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day05().testStep1()
    @Test @JsName("testDay05Step2") fun `Day 05 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day05().testStep2()
    @Test @JsName("testDay06Step1") fun `Day 06 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day06().testStep1()
    @Test @JsName("testDay06Step2") fun `Day 06 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day06().testStep2()
    @Test @JsName("testDay07Step1") fun `Day 07 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day07().testStep1()
    @Test @JsName("testDay07Step2") fun `Day 07 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day07().testStep2()
    @Test @JsName("testDay08Step1") fun `Day 08 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day08().testStep1()
    @Test @JsName("testDay08Step2") fun `Day 08 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day08().testStep2()
    @Test @JsName("testDay09Step1") fun `Day 09 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day09().testStep1()
    @Test @JsName("testDay09Step2") fun `Day 09 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day09().testStep2()
    @Test @JsName("testDay10Step1") fun `Day 10 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day10().testStep1()
    @Test @JsName("testDay10Step2") fun `Day 10 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day10().testStep2()
    @Test @JsName("testDay11Step1") fun `Day 11 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day11().testStep1()
    @Test @JsName("testDay11Step2") fun `Day 11 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day11().testStep2()
    @Test @JsName("testDay12Step1") fun `Day 12 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day12().testStep1()
    @Test @JsName("testDay12Step2") fun `Day 12 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day12().testStep2()
    @Test @JsName("testDay13Step1") fun `Day 13 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day13().testStep1()
    @Test @JsName("testDay13Step2") fun `Day 13 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day13().testStep2()
    @Test @JsName("testDay14Step1") fun `Day 14 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day14().testStep1()
    @Test @JsName("testDay14Step2") fun `Day 14 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day14().testStep2()
    @Test @JsName("testDay15Step1") fun `Day 15 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day15().testStep1()
    @Test @JsName("testDay15Step2") fun `Day 15 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day15().testStep2()
    @Test @JsName("testDay16Step1") fun `Day 16 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day16().testStep1()
    @Test @JsName("testDay16Step2") fun `Day 16 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day16().testStep2()
    @Test @JsName("testDay17Step1") fun `Day 17 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day17().testStep1()
    @Test @JsName("testDay17Step2") fun `Day 17 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day17().testStep2()
    @Test @JsName("testDay18Step1") fun `Day 18 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day18().testStep1()
    @Test @JsName("testDay18Step2") fun `Day 18 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day18().testStep2()
    @Test @JsName("testDay19Step1") fun `Day 19 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day19().testStep1()
    @Test @JsName("testDay19Step2") fun `Day 19 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day19().testStep2()
    @Test @JsName("testDay20Step1") fun `Day 20 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day20().testStep1()
    @Test @JsName("testDay20Step2") fun `Day 20 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day20().testStep2()
    @Test @JsName("testDay21Step1") fun `Day 21 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day21().testStep1()
    @Test @JsName("testDay21Step2") fun `Day 21 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day21().testStep2()
    @Test @JsName("testDay22Step1") fun `Day 22 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day22().testStep1()
    @Test @JsName("testDay22Step2") fun `Day 22 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day22().testStep2()
    @Test @JsName("testDay23Step1") fun `Day 23 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day23().testStep1()
    @Test @JsName("testDay23Step2") fun `Day 23 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day23().testStep2()
    @Test @JsName("testDay24Step1") fun `Day 24 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day24().testStep1()
    @Test @JsName("testDay24Step2") fun `Day 24 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day24().testStep2()
    @Test @JsName("testDay25Step1") fun `Day 25 step 1`() = fr.outadoc.aoc.twentytwentytwo.Day25().testStep1()
    @Test @JsName("testDay25Step2") fun `Day 25 step 2`() = fr.outadoc.aoc.twentytwentytwo.Day25().testStep2()
}
